import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Code Connect",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-BR">
            <body className="min-h-screen flex flex-col bg-gradient-main">
                {children}
            </body>
        </html>
    );
}
